spring:
  main:
    banner-mode: off
    web-application-type: none
  ai:
    mcp:
      server:
        name: my-mcp
        version: 1.0.0
#logging:
#  level:
#    root: OFF
allowed:
  dirs: ${ALLOWED_DIRS}
app:
  screenshots:
    api-key: ${SCREENSHOTS_API_KEY}