name: Package Project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/my-mcp:latest .

      - name: Tag Docker image with version
        run: docker tag ghcr.io/${{ github.repository_owner }}/my-mcp:latest ghcr.io/${{ github.repository_owner }}/my-mcp:${{ github.sha }}

      - name: Push Docker image with version
        run: docker push ghcr.io/${{ github.repository_owner }}/my-mcp:${{ github.sha }}

      - name: Push Docker image with latest tag
        run: docker push ghcr.io/${{ github.repository_owner }}/my-mcp:latest