name: PR Check

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew build

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest || echo "Checkstyle not configured"

      - name: Run PMD
        run: ./gradlew pmdMain pmdTest || echo "PMD not configured"

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain spotbugsTest || echo "SpotBugs not configured"